import { defineElement } from '@umbraco-ui/uui-base/lib/registration';
import { css, html, LitElement } from 'lit';
import { property, state } from 'lit/decorators.js';
import { ActiveMixin, SelectableMixin } from 'packages/uui-base/lib/mixins';
import { UUISelectListEvent } from './UUISelectListEvent';

/**
 * @element country-select-example
 */
@defineElement('country-select-example')
export class CountrySelectExample extends LitElement {
  static styles = [
    css`
      :host {
        position: relative;
      }

      uui-input {
        width: 400px;
      }

      uui-select-list {
        display: flex;
        flex-direction: column;
        border: 1px solid black;
        width: 400px;
        max-height: 500px;
        overflow: auto;
        border: 1px solid #333333;
      }

      .region {
        text-align: center;
        padding: 8px;
        font-weight: bold;
        color: #333333;
        border-top: 1px solid #333333;
      }

      uui-select-option {
        padding: 8px 8px;
      }
    `,
  ];

  @property({ attribute: false })
  value: any[] = [];

  @property({ type: Boolean })
  multiselect = true;

  @state()
  search: string = '';

  private _renderCountry = (country: any) => html`<uui-select-option
    .value=${country}>
    ${country['Country or Area']}
  </uui-select-option>`;

  private _renderRegion = (region: any) => html`
    <span class="region">${region.name}</span>
    ${region.countries.map((country: any) => this._renderCountry(country))}
  `;

  private _onSelectChange = (e: any) => {
    this.value = e.detail.selected;
  };

  private get valueDisplay() {
    return this.value.map(country => country['Country or Area']).join(', ');
  }

  private _onInput = (e: any) => {
    this.search = e.target.value;
  };

  private _filterOptions = (): any[] => {
    const filteredRegions = regions.filter(region =>
      region.countries.some((country: any) =>
        country['Country or Area']
          .toLowerCase()
          .includes(this.search.toLowerCase())
      )
    );

    const filterFinal = filteredRegions.map(region => ({
      name: region.name,
      countries: region.countries.filter((country: any) =>
        country['Country or Area']
          .toLowerCase()
          .includes(this.search.toLowerCase())
      ),
    }));

    return filterFinal;
  };

  render() {
    return html`
      <input type="text" .value=${this.valueDisplay} @input=${this._onInput} />
      <uui-select-list
        ?multiselect=${this.multiselect}
        @change=${this._onSelectChange}>
        ${this._filterOptions().map(region => this._renderRegion(region))}
      </uui-select-list>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'country-select-example': CountrySelectExample;
  }
}

const regions: Array<any> = [
  {
    name: 'Africa',
    countries: [
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': '015',
        'Sub-region Name': 'Northern Africa',
        'Country or Area': 'Algeria',
        'M49 Code': '012',
        'ISO-alpha2 Code': 'DZ',
        'ISO-alpha3 Code': 'DZA',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': '015',
        'Sub-region Name': 'Northern Africa',
        'Country or Area': 'Egypt',
        'M49 Code': 818,
        'ISO-alpha2 Code': 'EG',
        'ISO-alpha3 Code': 'EGY',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': '015',
        'Sub-region Name': 'Northern Africa',
        'Country or Area': 'Libya',
        'M49 Code': 434,
        'ISO-alpha2 Code': 'LY',
        'ISO-alpha3 Code': 'LBY',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': '015',
        'Sub-region Name': 'Northern Africa',
        'Country or Area': 'Morocco',
        'M49 Code': 504,
        'ISO-alpha2 Code': 'MA',
        'ISO-alpha3 Code': 'MAR',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': '015',
        'Sub-region Name': 'Northern Africa',
        'Country or Area': 'Sudan',
        'M49 Code': 729,
        'ISO-alpha2 Code': 'SD',
        'ISO-alpha3 Code': 'SDN',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': '015',
        'Sub-region Name': 'Northern Africa',
        'Country or Area': 'Tunisia',
        'M49 Code': 788,
        'ISO-alpha2 Code': 'TN',
        'ISO-alpha3 Code': 'TUN',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': '015',
        'Sub-region Name': 'Northern Africa',
        'Country or Area': 'Western Sahara',
        'M49 Code': 732,
        'ISO-alpha2 Code': 'EH',
        'ISO-alpha3 Code': 'ESH',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'British Indian Ocean Territory',
        'M49 Code': '086',
        'ISO-alpha2 Code': 'IO',
        'ISO-alpha3 Code': 'IOT',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Burundi',
        'M49 Code': 108,
        'ISO-alpha2 Code': 'BI',
        'ISO-alpha3 Code': 'BDI',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Comoros',
        'M49 Code': 174,
        'ISO-alpha2 Code': 'KM',
        'ISO-alpha3 Code': 'COM',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Djibouti',
        'M49 Code': 262,
        'ISO-alpha2 Code': 'DJ',
        'ISO-alpha3 Code': 'DJI',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Eritrea',
        'M49 Code': 232,
        'ISO-alpha2 Code': 'ER',
        'ISO-alpha3 Code': 'ERI',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Ethiopia',
        'M49 Code': 231,
        'ISO-alpha2 Code': 'ET',
        'ISO-alpha3 Code': 'ETH',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'French Southern Territories',
        'M49 Code': 260,
        'ISO-alpha2 Code': 'TF',
        'ISO-alpha3 Code': 'ATF',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Kenya',
        'M49 Code': 404,
        'ISO-alpha2 Code': 'KE',
        'ISO-alpha3 Code': 'KEN',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Madagascar',
        'M49 Code': 450,
        'ISO-alpha2 Code': 'MG',
        'ISO-alpha3 Code': 'MDG',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Malawi',
        'M49 Code': 454,
        'ISO-alpha2 Code': 'MW',
        'ISO-alpha3 Code': 'MWI',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Mauritius',
        'M49 Code': 480,
        'ISO-alpha2 Code': 'MU',
        'ISO-alpha3 Code': 'MUS',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Mayotte',
        'M49 Code': 175,
        'ISO-alpha2 Code': 'YT',
        'ISO-alpha3 Code': 'MYT',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Mozambique',
        'M49 Code': 508,
        'ISO-alpha2 Code': 'MZ',
        'ISO-alpha3 Code': 'MOZ',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Réunion',
        'M49 Code': 638,
        'ISO-alpha2 Code': 'RE',
        'ISO-alpha3 Code': 'REU',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Rwanda',
        'M49 Code': 646,
        'ISO-alpha2 Code': 'RW',
        'ISO-alpha3 Code': 'RWA',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Seychelles',
        'M49 Code': 690,
        'ISO-alpha2 Code': 'SC',
        'ISO-alpha3 Code': 'SYC',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Somalia',
        'M49 Code': 706,
        'ISO-alpha2 Code': 'SO',
        'ISO-alpha3 Code': 'SOM',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'South Sudan',
        'M49 Code': 728,
        'ISO-alpha2 Code': 'SS',
        'ISO-alpha3 Code': 'SSD',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Uganda',
        'M49 Code': 800,
        'ISO-alpha2 Code': 'UG',
        'ISO-alpha3 Code': 'UGA',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'United Republic of Tanzania',
        'M49 Code': 834,
        'ISO-alpha2 Code': 'TZ',
        'ISO-alpha3 Code': 'TZA',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Zambia',
        'M49 Code': 894,
        'ISO-alpha2 Code': 'ZM',
        'ISO-alpha3 Code': 'ZMB',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Zimbabwe',
        'M49 Code': 716,
        'ISO-alpha2 Code': 'ZW',
        'ISO-alpha3 Code': 'ZWE',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Angola',
        'M49 Code': '024',
        'ISO-alpha2 Code': 'AO',
        'ISO-alpha3 Code': 'AGO',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Cameroon',
        'M49 Code': 120,
        'ISO-alpha2 Code': 'CM',
        'ISO-alpha3 Code': 'CMR',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Central African Republic',
        'M49 Code': 140,
        'ISO-alpha2 Code': 'CF',
        'ISO-alpha3 Code': 'CAF',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Chad',
        'M49 Code': 148,
        'ISO-alpha2 Code': 'TD',
        'ISO-alpha3 Code': 'TCD',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Congo',
        'M49 Code': 178,
        'ISO-alpha2 Code': 'CG',
        'ISO-alpha3 Code': 'COG',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Democratic Republic of the Congo',
        'M49 Code': 180,
        'ISO-alpha2 Code': 'CD',
        'ISO-alpha3 Code': 'COD',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Equatorial Guinea',
        'M49 Code': 226,
        'ISO-alpha2 Code': 'GQ',
        'ISO-alpha3 Code': 'GNQ',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Gabon',
        'M49 Code': 266,
        'ISO-alpha2 Code': 'GA',
        'ISO-alpha3 Code': 'GAB',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Sao Tome and Principe',
        'M49 Code': 678,
        'ISO-alpha2 Code': 'ST',
        'ISO-alpha3 Code': 'STP',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Botswana',
        'M49 Code': '072',
        'ISO-alpha2 Code': 'BW',
        'ISO-alpha3 Code': 'BWA',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Eswatini',
        'M49 Code': 748,
        'ISO-alpha2 Code': 'SZ',
        'ISO-alpha3 Code': 'SWZ',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Lesotho',
        'M49 Code': 426,
        'ISO-alpha2 Code': 'LS',
        'ISO-alpha3 Code': 'LSO',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Namibia',
        'M49 Code': 516,
        'ISO-alpha2 Code': 'NA',
        'ISO-alpha3 Code': 'NAM',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'South Africa',
        'M49 Code': 710,
        'ISO-alpha2 Code': 'ZA',
        'ISO-alpha3 Code': 'ZAF',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Benin',
        'M49 Code': 204,
        'ISO-alpha2 Code': 'BJ',
        'ISO-alpha3 Code': 'BEN',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Burkina Faso',
        'M49 Code': 854,
        'ISO-alpha2 Code': 'BF',
        'ISO-alpha3 Code': 'BFA',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Cabo Verde',
        'M49 Code': 132,
        'ISO-alpha2 Code': 'CV',
        'ISO-alpha3 Code': 'CPV',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Côte d’Ivoire',
        'M49 Code': 384,
        'ISO-alpha2 Code': 'CI',
        'ISO-alpha3 Code': 'CIV',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Gambia',
        'M49 Code': 270,
        'ISO-alpha2 Code': 'GM',
        'ISO-alpha3 Code': 'GMB',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Ghana',
        'M49 Code': 288,
        'ISO-alpha2 Code': 'GH',
        'ISO-alpha3 Code': 'GHA',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Guinea',
        'M49 Code': 324,
        'ISO-alpha2 Code': 'GN',
        'ISO-alpha3 Code': 'GIN',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Guinea-Bissau',
        'M49 Code': 624,
        'ISO-alpha2 Code': 'GW',
        'ISO-alpha3 Code': 'GNB',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Liberia',
        'M49 Code': 430,
        'ISO-alpha2 Code': 'LR',
        'ISO-alpha3 Code': 'LBR',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Mali',
        'M49 Code': 466,
        'ISO-alpha2 Code': 'ML',
        'ISO-alpha3 Code': 'MLI',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Mauritania',
        'M49 Code': 478,
        'ISO-alpha2 Code': 'MR',
        'ISO-alpha3 Code': 'MRT',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Niger',
        'M49 Code': 562,
        'ISO-alpha2 Code': 'NE',
        'ISO-alpha3 Code': 'NER',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Nigeria',
        'M49 Code': 566,
        'ISO-alpha2 Code': 'NG',
        'ISO-alpha3 Code': 'NGA',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Saint Helena',
        'M49 Code': 654,
        'ISO-alpha2 Code': 'SH',
        'ISO-alpha3 Code': 'SHN',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Senegal',
        'M49 Code': 686,
        'ISO-alpha2 Code': 'SN',
        'ISO-alpha3 Code': 'SEN',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Sierra Leone',
        'M49 Code': 694,
        'ISO-alpha2 Code': 'SL',
        'ISO-alpha3 Code': 'SLE',
      },
      {
        'Region Code': '002',
        'Region Name': 'Africa',
        'Sub-region Code': 202,
        'Sub-region Name': 'Sub-Saharan Africa',
        'Country or Area': 'Togo',
        'M49 Code': 768,
        'ISO-alpha2 Code': 'TG',
        'ISO-alpha3 Code': 'TGO',
      },
    ],
  },
  {
    name: 'Americas',
    countries: [
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Anguilla',
        'M49 Code': 660,
        'ISO-alpha2 Code': 'AI',
        'ISO-alpha3 Code': 'AIA',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Antigua and Barbuda',
        'M49 Code': '028',
        'ISO-alpha2 Code': 'AG',
        'ISO-alpha3 Code': 'ATG',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Aruba',
        'M49 Code': 533,
        'ISO-alpha2 Code': 'AW',
        'ISO-alpha3 Code': 'ABW',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Bahamas',
        'M49 Code': '044',
        'ISO-alpha2 Code': 'BS',
        'ISO-alpha3 Code': 'BHS',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Barbados',
        'M49 Code': '052',
        'ISO-alpha2 Code': 'BB',
        'ISO-alpha3 Code': 'BRB',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Bonaire',
        'M49 Code': 'Sint Eustatius and Saba',
        'ISO-alpha2 Code': 535,
        'ISO-alpha3 Code': 'BQ',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'British Virgin Islands',
        'M49 Code': '092',
        'ISO-alpha2 Code': 'VG',
        'ISO-alpha3 Code': 'VGB',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Cayman Islands',
        'M49 Code': 136,
        'ISO-alpha2 Code': 'KY',
        'ISO-alpha3 Code': 'CYM',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Cuba',
        'M49 Code': 192,
        'ISO-alpha2 Code': 'CU',
        'ISO-alpha3 Code': 'CUB',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Curaçao',
        'M49 Code': 531,
        'ISO-alpha2 Code': 'CW',
        'ISO-alpha3 Code': 'CUW',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Dominica',
        'M49 Code': 212,
        'ISO-alpha2 Code': 'DM',
        'ISO-alpha3 Code': 'DMA',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Dominican Republic',
        'M49 Code': 214,
        'ISO-alpha2 Code': 'DO',
        'ISO-alpha3 Code': 'DOM',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Grenada',
        'M49 Code': 308,
        'ISO-alpha2 Code': 'GD',
        'ISO-alpha3 Code': 'GRD',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Guadeloupe',
        'M49 Code': 312,
        'ISO-alpha2 Code': 'GP',
        'ISO-alpha3 Code': 'GLP',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Haiti',
        'M49 Code': 332,
        'ISO-alpha2 Code': 'HT',
        'ISO-alpha3 Code': 'HTI',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Jamaica',
        'M49 Code': 388,
        'ISO-alpha2 Code': 'JM',
        'ISO-alpha3 Code': 'JAM',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Martinique',
        'M49 Code': 474,
        'ISO-alpha2 Code': 'MQ',
        'ISO-alpha3 Code': 'MTQ',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Montserrat',
        'M49 Code': 500,
        'ISO-alpha2 Code': 'MS',
        'ISO-alpha3 Code': 'MSR',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Puerto Rico',
        'M49 Code': 630,
        'ISO-alpha2 Code': 'PR',
        'ISO-alpha3 Code': 'PRI',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Saint Barthélemy',
        'M49 Code': 652,
        'ISO-alpha2 Code': 'BL',
        'ISO-alpha3 Code': 'BLM',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Saint Kitts and Nevis',
        'M49 Code': 659,
        'ISO-alpha2 Code': 'KN',
        'ISO-alpha3 Code': 'KNA',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Saint Lucia',
        'M49 Code': 662,
        'ISO-alpha2 Code': 'LC',
        'ISO-alpha3 Code': 'LCA',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Saint Martin (French Part)',
        'M49 Code': 663,
        'ISO-alpha2 Code': 'MF',
        'ISO-alpha3 Code': 'MAF',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Saint Vincent and the Grenadines',
        'M49 Code': 670,
        'ISO-alpha2 Code': 'VC',
        'ISO-alpha3 Code': 'VCT',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Sint Maarten (Dutch part)',
        'M49 Code': 534,
        'ISO-alpha2 Code': 'SX',
        'ISO-alpha3 Code': 'SXM',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Trinidad and Tobago',
        'M49 Code': 780,
        'ISO-alpha2 Code': 'TT',
        'ISO-alpha3 Code': 'TTO',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Turks and Caicos Islands',
        'M49 Code': 796,
        'ISO-alpha2 Code': 'TC',
        'ISO-alpha3 Code': 'TCA',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'United States Virgin Islands',
        'M49 Code': 850,
        'ISO-alpha2 Code': 'VI',
        'ISO-alpha3 Code': 'VIR',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Belize',
        'M49 Code': '084',
        'ISO-alpha2 Code': 'BZ',
        'ISO-alpha3 Code': 'BLZ',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Costa Rica',
        'M49 Code': 188,
        'ISO-alpha2 Code': 'CR',
        'ISO-alpha3 Code': 'CRI',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'El Salvador',
        'M49 Code': 222,
        'ISO-alpha2 Code': 'SV',
        'ISO-alpha3 Code': 'SLV',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Guatemala',
        'M49 Code': 320,
        'ISO-alpha2 Code': 'GT',
        'ISO-alpha3 Code': 'GTM',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Honduras',
        'M49 Code': 340,
        'ISO-alpha2 Code': 'HN',
        'ISO-alpha3 Code': 'HND',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Mexico',
        'M49 Code': 484,
        'ISO-alpha2 Code': 'MX',
        'ISO-alpha3 Code': 'MEX',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Nicaragua',
        'M49 Code': 558,
        'ISO-alpha2 Code': 'NI',
        'ISO-alpha3 Code': 'NIC',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Panama',
        'M49 Code': 591,
        'ISO-alpha2 Code': 'PA',
        'ISO-alpha3 Code': 'PAN',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Argentina',
        'M49 Code': '032',
        'ISO-alpha2 Code': 'AR',
        'ISO-alpha3 Code': 'ARG',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Bolivia (Plurinational State of)',
        'M49 Code': '068',
        'ISO-alpha2 Code': 'BO',
        'ISO-alpha3 Code': 'BOL',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Bouvet Island',
        'M49 Code': '074',
        'ISO-alpha2 Code': 'BV',
        'ISO-alpha3 Code': 'BVT',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Brazil',
        'M49 Code': '076',
        'ISO-alpha2 Code': 'BR',
        'ISO-alpha3 Code': 'BRA',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Chile',
        'M49 Code': 152,
        'ISO-alpha2 Code': 'CL',
        'ISO-alpha3 Code': 'CHL',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Colombia',
        'M49 Code': 170,
        'ISO-alpha2 Code': 'CO',
        'ISO-alpha3 Code': 'COL',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Ecuador',
        'M49 Code': 218,
        'ISO-alpha2 Code': 'EC',
        'ISO-alpha3 Code': 'ECU',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Falkland Islands (Malvinas)',
        'M49 Code': 238,
        'ISO-alpha2 Code': 'FK',
        'ISO-alpha3 Code': 'FLK',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'French Guiana',
        'M49 Code': 254,
        'ISO-alpha2 Code': 'GF',
        'ISO-alpha3 Code': 'GUF',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Guyana',
        'M49 Code': 328,
        'ISO-alpha2 Code': 'GY',
        'ISO-alpha3 Code': 'GUY',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Paraguay',
        'M49 Code': 600,
        'ISO-alpha2 Code': 'PY',
        'ISO-alpha3 Code': 'PRY',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Peru',
        'M49 Code': 604,
        'ISO-alpha2 Code': 'PE',
        'ISO-alpha3 Code': 'PER',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'South Georgia and the South Sandwich Islands',
        'M49 Code': 239,
        'ISO-alpha2 Code': 'GS',
        'ISO-alpha3 Code': 'SGS',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Suriname',
        'M49 Code': 740,
        'ISO-alpha2 Code': 'SR',
        'ISO-alpha3 Code': 'SUR',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Uruguay',
        'M49 Code': 858,
        'ISO-alpha2 Code': 'UY',
        'ISO-alpha3 Code': 'URY',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': 419,
        'Sub-region Name': 'Latin America and the Caribbean',
        'Country or Area': 'Venezuela (Bolivarian Republic of)',
        'M49 Code': 862,
        'ISO-alpha2 Code': 'VE',
        'ISO-alpha3 Code': 'VEN',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': '021',
        'Sub-region Name': 'Northern America',
        'Country or Area': 'Bermuda',
        'M49 Code': '060',
        'ISO-alpha2 Code': 'BM',
        'ISO-alpha3 Code': 'BMU',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': '021',
        'Sub-region Name': 'Northern America',
        'Country or Area': 'Canada',
        'M49 Code': 124,
        'ISO-alpha2 Code': 'CA',
        'ISO-alpha3 Code': 'CAN',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': '021',
        'Sub-region Name': 'Northern America',
        'Country or Area': 'Greenland',
        'M49 Code': 304,
        'ISO-alpha2 Code': 'GL',
        'ISO-alpha3 Code': 'GRL',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': '021',
        'Sub-region Name': 'Northern America',
        'Country or Area': 'Saint Pierre and Miquelon',
        'M49 Code': 666,
        'ISO-alpha2 Code': 'PM',
        'ISO-alpha3 Code': 'SPM',
      },
      {
        'Region Code': '019',
        'Region Name': 'Americas',
        'Sub-region Code': '021',
        'Sub-region Name': 'Northern America',
        'Country or Area': 'United States of America',
        'M49 Code': 840,
        'ISO-alpha2 Code': 'US',
        'ISO-alpha3 Code': 'USA',
      },
    ],
  },
  {
    name: 'Asia',
    countries: [
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 143,
        'Sub-region Name': 'Central Asia',
        'Country or Area': 'Kazakhstan',
        'M49 Code': 398,
        'ISO-alpha2 Code': 'KZ',
        'ISO-alpha3 Code': 'KAZ',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 143,
        'Sub-region Name': 'Central Asia',
        'Country or Area': 'Kyrgyzstan',
        'M49 Code': 417,
        'ISO-alpha2 Code': 'KG',
        'ISO-alpha3 Code': 'KGZ',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 143,
        'Sub-region Name': 'Central Asia',
        'Country or Area': 'Tajikistan',
        'M49 Code': 762,
        'ISO-alpha2 Code': 'TJ',
        'ISO-alpha3 Code': 'TJK',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 143,
        'Sub-region Name': 'Central Asia',
        'Country or Area': 'Turkmenistan',
        'M49 Code': 795,
        'ISO-alpha2 Code': 'TM',
        'ISO-alpha3 Code': 'TKM',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 143,
        'Sub-region Name': 'Central Asia',
        'Country or Area': 'Uzbekistan',
        'M49 Code': 860,
        'ISO-alpha2 Code': 'UZ',
        'ISO-alpha3 Code': 'UZB',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '030',
        'Sub-region Name': 'Eastern Asia',
        'Country or Area': 'China',
        'M49 Code': 156,
        'ISO-alpha2 Code': 'CN',
        'ISO-alpha3 Code': 'CHN',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '030',
        'Sub-region Name': 'Eastern Asia',
        'Country or Area': 'China',
        'M49 Code': 'Hong Kong Special Administrative Region',
        'ISO-alpha2 Code': 344,
        'ISO-alpha3 Code': 'HK',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '030',
        'Sub-region Name': 'Eastern Asia',
        'Country or Area': 'China',
        'M49 Code': 'Macao Special Administrative Region',
        'ISO-alpha2 Code': 446,
        'ISO-alpha3 Code': 'MO',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '030',
        'Sub-region Name': 'Eastern Asia',
        'Country or Area': "Democratic People's Republic of Korea",
        'M49 Code': 408,
        'ISO-alpha2 Code': 'KP',
        'ISO-alpha3 Code': 'PRK',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '030',
        'Sub-region Name': 'Eastern Asia',
        'Country or Area': 'Japan',
        'M49 Code': 392,
        'ISO-alpha2 Code': 'JP',
        'ISO-alpha3 Code': 'JPN',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '030',
        'Sub-region Name': 'Eastern Asia',
        'Country or Area': 'Mongolia',
        'M49 Code': 496,
        'ISO-alpha2 Code': 'MN',
        'ISO-alpha3 Code': 'MNG',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '030',
        'Sub-region Name': 'Eastern Asia',
        'Country or Area': 'Republic of Korea',
        'M49 Code': 410,
        'ISO-alpha2 Code': 'KR',
        'ISO-alpha3 Code': 'KOR',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Brunei Darussalam',
        'M49 Code': '096',
        'ISO-alpha2 Code': 'BN',
        'ISO-alpha3 Code': 'BRN',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Cambodia',
        'M49 Code': 116,
        'ISO-alpha2 Code': 'KH',
        'ISO-alpha3 Code': 'KHM',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Indonesia',
        'M49 Code': 360,
        'ISO-alpha2 Code': 'ID',
        'ISO-alpha3 Code': 'IDN',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': "Lao People's Democratic Republic",
        'M49 Code': 418,
        'ISO-alpha2 Code': 'LA',
        'ISO-alpha3 Code': 'LAO',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Malaysia',
        'M49 Code': 458,
        'ISO-alpha2 Code': 'MY',
        'ISO-alpha3 Code': 'MYS',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Myanmar',
        'M49 Code': 104,
        'ISO-alpha2 Code': 'MM',
        'ISO-alpha3 Code': 'MMR',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Philippines',
        'M49 Code': 608,
        'ISO-alpha2 Code': 'PH',
        'ISO-alpha3 Code': 'PHL',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Singapore',
        'M49 Code': 702,
        'ISO-alpha2 Code': 'SG',
        'ISO-alpha3 Code': 'SGP',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Thailand',
        'M49 Code': 764,
        'ISO-alpha2 Code': 'TH',
        'ISO-alpha3 Code': 'THA',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Timor-Leste',
        'M49 Code': 626,
        'ISO-alpha2 Code': 'TL',
        'ISO-alpha3 Code': 'TLS',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '035',
        'Sub-region Name': 'South-eastern Asia',
        'Country or Area': 'Viet Nam',
        'M49 Code': 704,
        'ISO-alpha2 Code': 'VN',
        'ISO-alpha3 Code': 'VNM',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '034',
        'Sub-region Name': 'Southern Asia',
        'Country or Area': 'Afghanistan',
        'M49 Code': '004',
        'ISO-alpha2 Code': 'AF',
        'ISO-alpha3 Code': 'AFG',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '034',
        'Sub-region Name': 'Southern Asia',
        'Country or Area': 'Bangladesh',
        'M49 Code': '050',
        'ISO-alpha2 Code': 'BD',
        'ISO-alpha3 Code': 'BGD',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '034',
        'Sub-region Name': 'Southern Asia',
        'Country or Area': 'Bhutan',
        'M49 Code': '064',
        'ISO-alpha2 Code': 'BT',
        'ISO-alpha3 Code': 'BTN',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '034',
        'Sub-region Name': 'Southern Asia',
        'Country or Area': 'India',
        'M49 Code': 356,
        'ISO-alpha2 Code': 'IN',
        'ISO-alpha3 Code': 'IND',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '034',
        'Sub-region Name': 'Southern Asia',
        'Country or Area': 'Iran (Islamic Republic of)',
        'M49 Code': 364,
        'ISO-alpha2 Code': 'IR',
        'ISO-alpha3 Code': 'IRN',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '034',
        'Sub-region Name': 'Southern Asia',
        'Country or Area': 'Maldives',
        'M49 Code': 462,
        'ISO-alpha2 Code': 'MV',
        'ISO-alpha3 Code': 'MDV',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '034',
        'Sub-region Name': 'Southern Asia',
        'Country or Area': 'Nepal',
        'M49 Code': 524,
        'ISO-alpha2 Code': 'NP',
        'ISO-alpha3 Code': 'NPL',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '034',
        'Sub-region Name': 'Southern Asia',
        'Country or Area': 'Pakistan',
        'M49 Code': 586,
        'ISO-alpha2 Code': 'PK',
        'ISO-alpha3 Code': 'PAK',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': '034',
        'Sub-region Name': 'Southern Asia',
        'Country or Area': 'Sri Lanka',
        'M49 Code': 144,
        'ISO-alpha2 Code': 'LK',
        'ISO-alpha3 Code': 'LKA',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Armenia',
        'M49 Code': '051',
        'ISO-alpha2 Code': 'AM',
        'ISO-alpha3 Code': 'ARM',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Azerbaijan',
        'M49 Code': '031',
        'ISO-alpha2 Code': 'AZ',
        'ISO-alpha3 Code': 'AZE',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Bahrain',
        'M49 Code': '048',
        'ISO-alpha2 Code': 'BH',
        'ISO-alpha3 Code': 'BHR',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Cyprus',
        'M49 Code': 196,
        'ISO-alpha2 Code': 'CY',
        'ISO-alpha3 Code': 'CYP',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Georgia',
        'M49 Code': 268,
        'ISO-alpha2 Code': 'GE',
        'ISO-alpha3 Code': 'GEO',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Iraq',
        'M49 Code': 368,
        'ISO-alpha2 Code': 'IQ',
        'ISO-alpha3 Code': 'IRQ',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Israel',
        'M49 Code': 376,
        'ISO-alpha2 Code': 'IL',
        'ISO-alpha3 Code': 'ISR',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Jordan',
        'M49 Code': 400,
        'ISO-alpha2 Code': 'JO',
        'ISO-alpha3 Code': 'JOR',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Kuwait',
        'M49 Code': 414,
        'ISO-alpha2 Code': 'KW',
        'ISO-alpha3 Code': 'KWT',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Lebanon',
        'M49 Code': 422,
        'ISO-alpha2 Code': 'LB',
        'ISO-alpha3 Code': 'LBN',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Oman',
        'M49 Code': 512,
        'ISO-alpha2 Code': 'OM',
        'ISO-alpha3 Code': 'OMN',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Qatar',
        'M49 Code': 634,
        'ISO-alpha2 Code': 'QA',
        'ISO-alpha3 Code': 'QAT',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Saudi Arabia',
        'M49 Code': 682,
        'ISO-alpha2 Code': 'SA',
        'ISO-alpha3 Code': 'SAU',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'State of Palestine',
        'M49 Code': 275,
        'ISO-alpha2 Code': 'PS',
        'ISO-alpha3 Code': 'PSE',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Syrian Arab Republic',
        'M49 Code': 760,
        'ISO-alpha2 Code': 'SY',
        'ISO-alpha3 Code': 'SYR',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Turkey',
        'M49 Code': 792,
        'ISO-alpha2 Code': 'TR',
        'ISO-alpha3 Code': 'TUR',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'United Arab Emirates',
        'M49 Code': 784,
        'ISO-alpha2 Code': 'AE',
        'ISO-alpha3 Code': 'ARE',
      },
      {
        'Region Code': 142,
        'Region Name': 'Asia',
        'Sub-region Code': 145,
        'Sub-region Name': 'Western Asia',
        'Country or Area': 'Yemen',
        'M49 Code': 887,
        'ISO-alpha2 Code': 'YE',
        'ISO-alpha3 Code': 'YEM',
      },
    ],
  },
  {
    name: 'Europe',
    countries: [
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Belarus',
        'M49 Code': 112,
        'ISO-alpha2 Code': 'BY',
        'ISO-alpha3 Code': 'BLR',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Bulgaria',
        'M49 Code': 100,
        'ISO-alpha2 Code': 'BG',
        'ISO-alpha3 Code': 'BGR',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Czechia',
        'M49 Code': 203,
        'ISO-alpha2 Code': 'CZ',
        'ISO-alpha3 Code': 'CZE',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Hungary',
        'M49 Code': 348,
        'ISO-alpha2 Code': 'HU',
        'ISO-alpha3 Code': 'HUN',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Poland',
        'M49 Code': 616,
        'ISO-alpha2 Code': 'PL',
        'ISO-alpha3 Code': 'POL',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Republic of Moldova',
        'M49 Code': 498,
        'ISO-alpha2 Code': 'MD',
        'ISO-alpha3 Code': 'MDA',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Romania',
        'M49 Code': 642,
        'ISO-alpha2 Code': 'RO',
        'ISO-alpha3 Code': 'ROU',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Russian Federation',
        'M49 Code': 643,
        'ISO-alpha2 Code': 'RU',
        'ISO-alpha3 Code': 'RUS',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Slovakia',
        'M49 Code': 703,
        'ISO-alpha2 Code': 'SK',
        'ISO-alpha3 Code': 'SVK',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 151,
        'Sub-region Name': 'Eastern Europe',
        'Country or Area': 'Ukraine',
        'M49 Code': 804,
        'ISO-alpha2 Code': 'UA',
        'ISO-alpha3 Code': 'UKR',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Åland Islands',
        'M49 Code': 248,
        'ISO-alpha2 Code': 'AX',
        'ISO-alpha3 Code': 'ALA',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Guernsey',
        'M49 Code': 831,
        'ISO-alpha2 Code': 'GG',
        'ISO-alpha3 Code': 'GGY',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Jersey',
        'M49 Code': 832,
        'ISO-alpha2 Code': 'JE',
        'ISO-alpha3 Code': 'JEY',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Sark',
        'M49 Code': 680,
        'ISO-alpha2 Code': '',
        'ISO-alpha3 Code': '',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Denmark',
        'M49 Code': 208,
        'ISO-alpha2 Code': 'DK',
        'ISO-alpha3 Code': 'DNK',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Estonia',
        'M49 Code': 233,
        'ISO-alpha2 Code': 'EE',
        'ISO-alpha3 Code': 'EST',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Faroe Islands',
        'M49 Code': 234,
        'ISO-alpha2 Code': 'FO',
        'ISO-alpha3 Code': 'FRO',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Finland',
        'M49 Code': 246,
        'ISO-alpha2 Code': 'FI',
        'ISO-alpha3 Code': 'FIN',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Iceland',
        'M49 Code': 352,
        'ISO-alpha2 Code': 'IS',
        'ISO-alpha3 Code': 'ISL',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Ireland',
        'M49 Code': 372,
        'ISO-alpha2 Code': 'IE',
        'ISO-alpha3 Code': 'IRL',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Isle of Man',
        'M49 Code': 833,
        'ISO-alpha2 Code': 'IM',
        'ISO-alpha3 Code': 'IMN',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Latvia',
        'M49 Code': 428,
        'ISO-alpha2 Code': 'LV',
        'ISO-alpha3 Code': 'LVA',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Lithuania',
        'M49 Code': 440,
        'ISO-alpha2 Code': 'LT',
        'ISO-alpha3 Code': 'LTU',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Norway',
        'M49 Code': 578,
        'ISO-alpha2 Code': 'NO',
        'ISO-alpha3 Code': 'NOR',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Svalbard and Jan Mayen Islands',
        'M49 Code': 744,
        'ISO-alpha2 Code': 'SJ',
        'ISO-alpha3 Code': 'SJM',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area': 'Sweden',
        'M49 Code': 752,
        'ISO-alpha2 Code': 'SE',
        'ISO-alpha3 Code': 'SWE',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 154,
        'Sub-region Name': 'Northern Europe',
        'Country or Area':
          'United Kingdom of Great Britain and Northern Ireland',
        'M49 Code': 826,
        'ISO-alpha2 Code': 'GB',
        'ISO-alpha3 Code': 'GBR',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Albania',
        'M49 Code': '008',
        'ISO-alpha2 Code': 'AL',
        'ISO-alpha3 Code': 'ALB',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Andorra',
        'M49 Code': '020',
        'ISO-alpha2 Code': 'AD',
        'ISO-alpha3 Code': 'AND',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Bosnia and Herzegovina',
        'M49 Code': '070',
        'ISO-alpha2 Code': 'BA',
        'ISO-alpha3 Code': 'BIH',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Croatia',
        'M49 Code': 191,
        'ISO-alpha2 Code': 'HR',
        'ISO-alpha3 Code': 'HRV',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Gibraltar',
        'M49 Code': 292,
        'ISO-alpha2 Code': 'GI',
        'ISO-alpha3 Code': 'GIB',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Greece',
        'M49 Code': 300,
        'ISO-alpha2 Code': 'GR',
        'ISO-alpha3 Code': 'GRC',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Holy See',
        'M49 Code': 336,
        'ISO-alpha2 Code': 'VA',
        'ISO-alpha3 Code': 'VAT',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Italy',
        'M49 Code': 380,
        'ISO-alpha2 Code': 'IT',
        'ISO-alpha3 Code': 'ITA',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Malta',
        'M49 Code': 470,
        'ISO-alpha2 Code': 'MT',
        'ISO-alpha3 Code': 'MLT',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Montenegro',
        'M49 Code': 499,
        'ISO-alpha2 Code': 'ME',
        'ISO-alpha3 Code': 'MNE',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'North Macedonia',
        'M49 Code': 807,
        'ISO-alpha2 Code': 'MK',
        'ISO-alpha3 Code': 'MKD',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Portugal',
        'M49 Code': 620,
        'ISO-alpha2 Code': 'PT',
        'ISO-alpha3 Code': 'PRT',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'San Marino',
        'M49 Code': 674,
        'ISO-alpha2 Code': 'SM',
        'ISO-alpha3 Code': 'SMR',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Serbia',
        'M49 Code': 688,
        'ISO-alpha2 Code': 'RS',
        'ISO-alpha3 Code': 'SRB',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Slovenia',
        'M49 Code': 705,
        'ISO-alpha2 Code': 'SI',
        'ISO-alpha3 Code': 'SVN',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': '039',
        'Sub-region Name': 'Southern Europe',
        'Country or Area': 'Spain',
        'M49 Code': 724,
        'ISO-alpha2 Code': 'ES',
        'ISO-alpha3 Code': 'ESP',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 155,
        'Sub-region Name': 'Western Europe',
        'Country or Area': 'Austria',
        'M49 Code': '040',
        'ISO-alpha2 Code': 'AT',
        'ISO-alpha3 Code': 'AUT',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 155,
        'Sub-region Name': 'Western Europe',
        'Country or Area': 'Belgium',
        'M49 Code': '056',
        'ISO-alpha2 Code': 'BE',
        'ISO-alpha3 Code': 'BEL',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 155,
        'Sub-region Name': 'Western Europe',
        'Country or Area': 'France',
        'M49 Code': 250,
        'ISO-alpha2 Code': 'FR',
        'ISO-alpha3 Code': 'FRA',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 155,
        'Sub-region Name': 'Western Europe',
        'Country or Area': 'Germany',
        'M49 Code': 276,
        'ISO-alpha2 Code': 'DE',
        'ISO-alpha3 Code': 'DEU',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 155,
        'Sub-region Name': 'Western Europe',
        'Country or Area': 'Liechtenstein',
        'M49 Code': 438,
        'ISO-alpha2 Code': 'LI',
        'ISO-alpha3 Code': 'LIE',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 155,
        'Sub-region Name': 'Western Europe',
        'Country or Area': 'Luxembourg',
        'M49 Code': 442,
        'ISO-alpha2 Code': 'LU',
        'ISO-alpha3 Code': 'LUX',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 155,
        'Sub-region Name': 'Western Europe',
        'Country or Area': 'Monaco',
        'M49 Code': 492,
        'ISO-alpha2 Code': 'MC',
        'ISO-alpha3 Code': 'MCO',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 155,
        'Sub-region Name': 'Western Europe',
        'Country or Area': 'Netherlands',
        'M49 Code': 528,
        'ISO-alpha2 Code': 'NL',
        'ISO-alpha3 Code': 'NLD',
      },
      {
        'Region Code': 150,
        'Region Name': 'Europe',
        'Sub-region Code': 155,
        'Sub-region Name': 'Western Europe',
        'Country or Area': 'Switzerland',
        'M49 Code': 756,
        'ISO-alpha2 Code': 'CH',
        'ISO-alpha3 Code': 'CHE',
      },
    ],
  },
  {
    name: 'Oceania',
    countries: [
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '053',
        'Sub-region Name': 'Australia and New Zealand',
        'Country or Area': 'Australia',
        'M49 Code': '036',
        'ISO-alpha2 Code': 'AU',
        'ISO-alpha3 Code': 'AUS',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '053',
        'Sub-region Name': 'Australia and New Zealand',
        'Country or Area': 'Christmas Island',
        'M49 Code': 162,
        'ISO-alpha2 Code': 'CX',
        'ISO-alpha3 Code': 'CXR',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '053',
        'Sub-region Name': 'Australia and New Zealand',
        'Country or Area': 'Cocos (Keeling) Islands',
        'M49 Code': 166,
        'ISO-alpha2 Code': 'CC',
        'ISO-alpha3 Code': 'CCK',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '053',
        'Sub-region Name': 'Australia and New Zealand',
        'Country or Area': 'Heard Island and McDonald Islands',
        'M49 Code': 334,
        'ISO-alpha2 Code': 'HM',
        'ISO-alpha3 Code': 'HMD',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '053',
        'Sub-region Name': 'Australia and New Zealand',
        'Country or Area': 'New Zealand',
        'M49 Code': 554,
        'ISO-alpha2 Code': 'NZ',
        'ISO-alpha3 Code': 'NZL',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '053',
        'Sub-region Name': 'Australia and New Zealand',
        'Country or Area': 'Norfolk Island',
        'M49 Code': 574,
        'ISO-alpha2 Code': 'NF',
        'ISO-alpha3 Code': 'NFK',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '054',
        'Sub-region Name': 'Melanesia',
        'Country or Area': 'Fiji',
        'M49 Code': 242,
        'ISO-alpha2 Code': 'FJ',
        'ISO-alpha3 Code': 'FJI',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '054',
        'Sub-region Name': 'Melanesia',
        'Country or Area': 'New Caledonia',
        'M49 Code': 540,
        'ISO-alpha2 Code': 'NC',
        'ISO-alpha3 Code': 'NCL',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '054',
        'Sub-region Name': 'Melanesia',
        'Country or Area': 'Papua New Guinea',
        'M49 Code': 598,
        'ISO-alpha2 Code': 'PG',
        'ISO-alpha3 Code': 'PNG',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '054',
        'Sub-region Name': 'Melanesia',
        'Country or Area': 'Solomon Islands',
        'M49 Code': '090',
        'ISO-alpha2 Code': 'SB',
        'ISO-alpha3 Code': 'SLB',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '054',
        'Sub-region Name': 'Melanesia',
        'Country or Area': 'Vanuatu',
        'M49 Code': 548,
        'ISO-alpha2 Code': 'VU',
        'ISO-alpha3 Code': 'VUT',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '057',
        'Sub-region Name': 'Micronesia',
        'Country or Area': 'Guam',
        'M49 Code': 316,
        'ISO-alpha2 Code': 'GU',
        'ISO-alpha3 Code': 'GUM',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '057',
        'Sub-region Name': 'Micronesia',
        'Country or Area': 'Kiribati',
        'M49 Code': 296,
        'ISO-alpha2 Code': 'KI',
        'ISO-alpha3 Code': 'KIR',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '057',
        'Sub-region Name': 'Micronesia',
        'Country or Area': 'Marshall Islands',
        'M49 Code': 584,
        'ISO-alpha2 Code': 'MH',
        'ISO-alpha3 Code': 'MHL',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '057',
        'Sub-region Name': 'Micronesia',
        'Country or Area': 'Micronesia (Federated States of)',
        'M49 Code': 583,
        'ISO-alpha2 Code': 'FM',
        'ISO-alpha3 Code': 'FSM',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '057',
        'Sub-region Name': 'Micronesia',
        'Country or Area': 'Nauru',
        'M49 Code': 520,
        'ISO-alpha2 Code': 'NR',
        'ISO-alpha3 Code': 'NRU',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '057',
        'Sub-region Name': 'Micronesia',
        'Country or Area': 'Northern Mariana Islands',
        'M49 Code': 580,
        'ISO-alpha2 Code': 'MP',
        'ISO-alpha3 Code': 'MNP',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '057',
        'Sub-region Name': 'Micronesia',
        'Country or Area': 'Palau',
        'M49 Code': 585,
        'ISO-alpha2 Code': 'PW',
        'ISO-alpha3 Code': 'PLW',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '057',
        'Sub-region Name': 'Micronesia',
        'Country or Area': 'United States Minor Outlying Islands',
        'M49 Code': 581,
        'ISO-alpha2 Code': 'UM',
        'ISO-alpha3 Code': 'UMI',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'American Samoa',
        'M49 Code': '016',
        'ISO-alpha2 Code': 'AS',
        'ISO-alpha3 Code': 'ASM',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'Cook Islands',
        'M49 Code': 184,
        'ISO-alpha2 Code': 'CK',
        'ISO-alpha3 Code': 'COK',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'French Polynesia',
        'M49 Code': 258,
        'ISO-alpha2 Code': 'PF',
        'ISO-alpha3 Code': 'PYF',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'Niue',
        'M49 Code': 570,
        'ISO-alpha2 Code': 'NU',
        'ISO-alpha3 Code': 'NIU',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'Pitcairn',
        'M49 Code': 612,
        'ISO-alpha2 Code': 'PN',
        'ISO-alpha3 Code': 'PCN',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'Samoa',
        'M49 Code': 882,
        'ISO-alpha2 Code': 'WS',
        'ISO-alpha3 Code': 'WSM',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'Tokelau',
        'M49 Code': 772,
        'ISO-alpha2 Code': 'TK',
        'ISO-alpha3 Code': 'TKL',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'Tonga',
        'M49 Code': 776,
        'ISO-alpha2 Code': 'TO',
        'ISO-alpha3 Code': 'TON',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'Tuvalu',
        'M49 Code': 798,
        'ISO-alpha2 Code': 'TV',
        'ISO-alpha3 Code': 'TUV',
      },
      {
        'Region Code': '009',
        'Region Name': 'Oceania',
        'Sub-region Code': '061',
        'Sub-region Name': 'Polynesia',
        'Country or Area': 'Wallis and Futuna Islands',
        'M49 Code': 876,
        'ISO-alpha2 Code': 'WF',
        'ISO-alpha3 Code': 'WLF',
      },
    ],
  },
  {
    name: 'Other',
    countries: [
      {
        'Region Code': '',
        'Region Name': '',
        'Sub-region Code': '',
        'Sub-region Name': '',
        'Country or Area': 'Antarctica',
        'M49 Code': '010',
        'ISO-alpha2 Code': 'AQ',
        'ISO-alpha3 Code': 'ATA',
      },
    ],
  },
];
