export default {
  customProperties: {
    '--uui-size-1': '3px',
    '--uui-size-2': '6px',
    '--uui-size-3': '9px',
    '--uui-size-4': '12px',
    '--uui-size-5': '15px',
    '--uui-size-6': '18px',
    '--uui-size-7': '21px',
    '--uui-size-8': '24px',
    '--uui-size-9': '27px',
    '--uui-size-10': '30px',
    '--uui-size-11': '33px',
    '--uui-size-12': '36px',
    '--uui-size-14': '42px',
    '--uui-size-16': '48px',
    '--uui-size-20': '60px',
    '--uui-size-22': '66px',
    '--uui-size-24': '72px',
    '--uui-size-28': '84px',
    '--uui-size-32': '96px',
    '--uui-size-36': '108px',
    '--uui-size-40': '120px',
    '--uui-size-44': '132px',
    '--uui-size-46': '138px',
    '--uui-size-48': '144px',
    '--uui-size-52': '156px',
    '--uui-size-56': '168px',
    '--uui-size-60': '180px',
    '--uui-size-64': '192px',
    '--uui-size-72': '216px',
    '--uui-size-80': '240px',
    '--uui-size-96': '288px',
    '--uui-size-100': '300px',
    '--uui-size-space-1': '3px',
    '--uui-size-space-2': '6px',
    '--uui-size-space-3': '9px',
    '--uui-size-space-4': '12px',
    '--uui-size-space-5': '18px',
    '--uui-size-space-6': '24px',
    '--uui-size-layout-1': '24px',
    '--uui-size-layout-2': '30px',
    '--uui-size-layout-3': '42px',
    '--uui-size-layout-4': '66px',
    '--uui-size-layout-5': '96px',
    '--uui-size-layout-6': '138px',
    '--uui-border-radius': '3px',
    '--uui-type-default-size': '14px',
    '--uui-type-small-size': '12px',
    '--uui-type-h1-size': '60px',
    '--uui-type-h2-size': '42px',
    '--uui-type-h3-size': '30px',
    '--uui-type-h4-size': '21px',
    '--uui-type-h5-size': '14px',
    '--uui-type-h6-size': '12px',
    '--uui-shadow-depth-1':
      '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
    '--uui-shadow-depth-2':
      '0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23)',
    '--uui-shadow-depth-3':
      '0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23)',
    '--uui-shadow-depth-4':
      '0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22)',
    '--uui-shadow-depth-5':
      '0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22)',
    '--uui-palette-deep-saffron': '#f79c37',
    '--uui-palette-deep-saffron-light':
      'rgb(\n    249,\n    181,\n    103\n  )',
    '--uui-palette-deep-saffron-dark': 'rgb(\n    222,\n    145,\n    56\n  )',
    '--uui-palette-deep-saffron-dimmed':
      'rgb(\n    166,\n    150,\n    133\n  )',
    '--uui-palette-sunglow': '#fad634',
    '--uui-palette-sunglow-light': 'rgb(\n    251,\n    224,\n    101\n  )',
    '--uui-palette-sunglow-dark': 'rgb(\n    224,\n    193,\n    51\n  )',
    '--uui-palette-sunglow-dimmed': 'rgb(\n    166,\n    160,\n    133\n  )',
    '--uui-palette-spanish-pink': '#f5c1bc',
    '--uui-palette-spanish-pink-light':
      'rgb(\n    248,\n    214,\n    211\n  )',
    '--uui-palette-spanish-pink-dark': 'rgb(\n    232,\n    192,\n    189\n  )',
    '--uui-palette-spanish-pink-dimmed':
      'rgb(\n    219,\n    212,\n    212\n  )',
    '--uui-palette-gunmetal': '#162335',
    '--uui-palette-gunmetal-light': 'rgb(\n    35,\n    55,\n    83\n  )',
    '--uui-palette-gunmetal-dark': 'rgb(\n    23,\n    27,\n    33\n  )',
    '--uui-palette-gunmetal-dimmed': 'rgb(\n    54,\n    54,\n    54\n  )',
    '--uui-palette-space-cadet': '#1b264f',
    '--uui-palette-space-cadet-light': 'rgb(\n    38,\n    53,\n    110\n  )',
    '--uui-palette-space-cadet-dark': 'rgb(\n    28,\n    35,\n    59\n  )',
    '--uui-palette-space-cadet-dimmed':
      'rgb(\n    106,\n    117,\n    154\n  )',
    '--uui-palette-violet-blue': '#3544b1',
    '--uui-palette-violet-blue-light': 'rgb(\n    70,\n    86,\n    200\n  )',
    '--uui-palette-violet-blue-dark': 'rgb(\n    54,\n    65,\n    156\n  )',
    '--uui-palette-violet-blue-dimmed': 'rgb(\n    87,\n    87,\n    87\n  )',
    '--uui-palette-malibu': '#3879ff',
    '--uui-palette-malibu-light': 'rgb(\n    97,\n    150,\n    255\n  )',
    '--uui-palette-malibu-dark': 'rgb(\n    56,\n    116,\n    235\n  )',
    '--uui-palette-malibu-dimmed': 'rgb(\n    115,\n    120,\n    130\n  )',
    '--uui-palette-maroon-flush': '#c31d4c',
    '--uui-palette-maroon-flush-light': 'rgb(\n    223,\n    42,\n    93\n  )',
    '--uui-palette-maroon-flush-dark': 'rgb(\n    174,\n    30,\n    71\n  )',
    '--uui-palette-maroon-flush-dimmed':
      'rgb(\n    122,\n    98,\n    104\n  )',
    '--uui-palette-jungle-green': '#2bc37c',
    '--uui-palette-jungle-green-light': 'rgb(\n    58,\n    212,\n    140\n  )',
    '--uui-palette-jungle-green-dark': 'rgb(\n    43,\n    179,\n    115\n  )',
    '--uui-palette-jungle-green-dimmed':
      'rgb(\n    102,\n    135,\n    120\n  )',
    '--uui-palette-forest-green': '#0b8152',
    '--uui-palette-forest-green-light': 'rgb(\n    13,\n    155,\n    98\n  )',
    '--uui-palette-forest-green-dark': 'rgb(\n    10,\n    115,\n    73\n  )',
    '--uui-palette-forest-green-dimmed': 'rgb(\n    46,\n    89,\n    72\n  )',
    '--uui-palette-cocoa-black': '#191715',
    '--uui-palette-cocoa-black-light': 'rgb(\n    39,\n    36,\n    32\n  )',
    '--uui-palette-cocoa-black-dark': 'rgb(\n    20,\n    20,\n    20\n  )',
    '--uui-palette-cocoa-black-dimmed': 'rgb(\n    48,\n    48,\n    48\n  )',
    '--uui-palette-dune-black': '#2e2b29',
    '--uui-palette-dune-black-light': 'rgb(\n    57,\n    53,\n    50\n  )',
    '--uui-palette-dune-black-dark': 'rgb(\n    38,\n    38,\n    38\n  )',
    '--uui-palette-dune-black-dimmed': 'rgb(\n    64,\n    64,\n    64\n  )',
    '--uui-palette-cocoa-brown': '#332a24',
    '--uui-palette-cocoa-brown-light': 'rgb(\n    66,\n    54,\n    47\n  )',
    '--uui-palette-cocoa-brown-dark': 'rgb(\n    38,\n    37,\n    36\n  )',
    '--uui-palette-cocoa-brown-dimmed': 'rgb(\n    43,\n    43,\n    43\n  )',
    '--uui-palette-chamoisee': '#9d8057',
    '--uui-palette-chamoisee-light': 'rgb(\n    175,\n    148,\n    110\n  )',
    '--uui-palette-chamoisee-dark': 'rgb(\n    138,\n    116,\n    87\n  )',
    '--uui-palette-chamoisee-dimmed': 'rgb(\n    115,\n    113,\n    110\n  )',
    '--uui-palette-timberwolf': '#e2dad4',
    '--uui-palette-timberwolf-light': 'rgb(\n    243,\n    239,\n    237\n  )',
    '--uui-palette-timberwolf-dark': 'rgb(\n    208,\n    208,\n    208\n  )',
    '--uui-palette-timberwolf-dimmed': 'rgb(\n    207,\n    207,\n    207\n  )',
    '--uui-palette-gravel': '#d8d7d9',
    '--uui-palette-gravel-light': 'rgb(\n    237,\n    237,\n    238\n  )',
    '--uui-palette-gravel-dark': 'rgb(\n    200,\n    200,\n    200\n  )',
    '--uui-palette-gravel-dimmed': 'rgb(\n    204,\n    204,\n    204\n  )',
    '--uui-palette-sand': '#f3f3f5',
    '--uui-palette-sand-light': 'rgb(\n    255,\n    255,\n    255\n  )',
    '--uui-palette-sand-dark': 'rgb(\n    226,\n    226,\n    226\n  )',
    '--uui-palette-sand-dimmed': 'rgb(\n    231,\n    231,\n    231\n  )',
    '--uui-palette-white': '#fefefe',
    '--uui-palette-white-light': 'rgb(\n    255,\n    255,\n    255\n  )',
    '--uui-palette-white-dark': 'rgb(\n    250,\n    250,\n    250\n  )',
    '--uui-palette-white-dimmed': 'rgb(\n    228,\n    228,\n    228\n  )',
    '--uui-palette-black': '#060606',
    '--uui-palette-black-light': 'rgb(\n    26,\n    26,\n    26\n  )',
    '--uui-palette-black-dark': 'rgb(5, 5, 5)',
    '--uui-palette-black-dimmed': 'rgb(\n    36,\n    36,\n    36\n  )',
    '--uui-palette-grey': '#c4c4c4',
    '--uui-palette-grey-light': 'rgb(\n    222,\n    222,\n    222\n  )',
    '--uui-palette-grey-dark': 'rgb(\n    179,\n    179,\n    179\n  )',
    '--uui-palette-grey-dimmed': 'rgb(\n    189,\n    189,\n    189\n  )',
    '--uui-palette-dusty-grey': '#9b9b9b',
    '--uui-palette-dusty-grey-light': 'rgb(\n    176,\n    176,\n    176\n  )',
    '--uui-palette-dusty-grey-dark': 'rgb(\n    141,\n    141,\n    141\n  )',
    '--uui-palette-dusty-grey-dimmed': 'rgb(\n    186,\n    186,\n    186\n  )',
    '--uui-palette-mine-grey': '#3e3e3e',
    '--uui-palette-mine-grey-light': 'rgb(\n    82,\n    82,\n    82\n  )',
    '--uui-palette-mine-grey-dark': 'rgb(\n    56,\n    56,\n    56\n  )',
    '--uui-palette-mine-grey-dimmed': 'rgb(\n    87,\n    87,\n    87\n  )',
    '--uui-color-selected': '#3544b1',
    '--uui-color-selected-emphasis': 'rgb(\n    70,\n    86,\n    200\n  )',
    '--uui-color-selected-standalone': 'rgb(\n    54,\n    65,\n    156\n  )',
    '--uui-color-selected-contrast': '#fff',
    '--uui-color-current': '#f5c1bc',
    '--uui-color-current-emphasis': 'rgb(\n    248,\n    214,\n    211\n  )',
    '--uui-color-current-standalone': 'rgb(\n    232,\n    192,\n    189\n  )',
    '--uui-color-current-contrast': '#1b264f',
    '--uui-color-disabled': '#f3f3f5',
    '--uui-color-disabled-standalone': 'rgb(\n    226,\n    226,\n    226\n  )',
    '--uui-color-disabled-contrast': '#c4c4c4',
    '--uui-color-header-surface': '#1b264f',
    '--uui-color-header-contrast': 'rgba(255, 255, 255, 0.8)',
    '--uui-color-header-contrast-emphasis': '#fff',
    '--uui-color-focus': '#3879ff',
    '--uui-color-surface': '#fff',
    '--uui-color-surface-alt': '#f3f3f5',
    '--uui-color-surface-emphasis': 'rgb(\n    250,\n    250,\n    250\n  )',
    '--uui-color-background': '#f3f3f5',
    '--uui-color-text': '#060606',
    '--uui-color-text-alt': '#2e2b29',
    '--uui-color-interactive': '#1b264f',
    '--uui-color-interactive-emphasis': '#3544b1',
    '--uui-color-border': '#d8d7d9',
    '--uui-color-border-standalone': '#c2c2c2',
    '--uui-color-border-emphasis': '#a1a1a1',
    '--uui-color-divider': '#f6f6f7',
    '--uui-color-divider-standalone': '#e9e9eb',
    '--uui-color-divider-emphasis': '#bdbdbd',
    '--uui-color-default': '#1b264f',
    '--uui-color-default-emphasis': '#3544b1',
    '--uui-color-default-standalone': 'rgb(\n    28,\n    35,\n    59\n  )',
    '--uui-color-default-contrast': '#fff',
    '--uui-color-warning': '#fbd142',
    '--uui-color-warning-emphasis': 'rgb(\n    251,\n    224,\n    101\n  )',
    '--uui-color-warning-standalone': '#a17700',
    '--uui-color-warning-contrast': '#000',
    '--uui-color-danger': '#c31d4c',
    '--uui-color-danger-emphasis': 'rgb(\n    223,\n    42,\n    93\n  )',
    '--uui-color-danger-standalone': 'rgb(\n    174,\n    30,\n    71\n  )',
    '--uui-color-danger-contrast': 'white',
    '--uui-color-invalid': '#c31d4c',
    '--uui-color-invalid-emphasis': 'rgb(\n    223,\n    42,\n    93\n  )',
    '--uui-color-invalid-standalone': 'rgb(\n    174,\n    30,\n    71\n  )',
    '--uui-color-invalid-contrast': 'white',
    '--uui-color-positive': '#0b8152',
    '--uui-color-positive-emphasis': 'rgb(\n    13,\n    155,\n    98\n  )',
    '--uui-color-positive-standalone': 'rgb(\n    10,\n    115,\n    73\n  )',
    '--uui-color-positive-contrast': '#fff',
    '--uui-font-family':
      "'Lato', 'Helvetica Neue', Helvetica, Arial, sans-serif",
  },
};
